### ISSUE TITLE
Drinking Ice Juice is too fast

### ISSUE THREAD

**Issue by pete-h** [Sparkierkan7/thermite_mod#1]
First I want to say thanks for this mod, I really like it :)

Now the issue I found:
Drinking ice juice is too fast. If I have a stack of ice juice and I click use, it goes through the stack of juice bottles really fast (leaving me with Hypothermia instead of overheating).

Drinking other potions or water bottles is much slower.

**Comment by Sparkierkan7** [comment]
Right now the Ice juice bottles don't play the little drinking animation like potions do. You just have to click once to use them.

**Comment by pete-h** [comment]
ah, I will get used to it being faster :)

**Comment by Sparkierkan7** [comment]
I'll try to add the animation to it in a future update.
