### ISSUE TITLE
Lagging/Ticking Issue in Survival SinglePlayer

### ISSUE THREAD

**Issue by NukeBrony** [Sparkierkan7/thermite_mod#11]
3 to 5 second delay for singleplayer survival events. did use mods but they shouldnt have affected it. used fabric seasons mod

**Comment by Dragom626** [comment]
Most recent version causing the same issue in my game, really bad delays in anything happening and eventually I somehow lag out of a single player world into the multiplayer menu.

**Comment by Sparkierkan7** [comment]
Do you guys have [C2ME](https://modrinth.com/mod/c2me-fabric) installed? Cause for some reason when its also installed the game lags a ton and can crash.

**Comment by NukeBrony** [comment]
yes i do. its part of an optimization modpack i need to run mc at a reasonable framrate

**Comment by Sparkierkan7** [comment]
I'm probably not going to be fixing this anytime soon so if you need to keep C2ME just use a different temperature mod.
