### ISSUE TITLE
Unlit campfire still heats

### ISSUE THREAD

**Issue by mettemfurfur000** [Sparkierkan7/thermite_mod#12]
looks like this:

![image](https://github.com/Sparkierkan7/thermite_mod/assets/94188324/5da4478e-9b94-4ec5-9f8e-148fd92b018c)

Can I change this behavior by changing the configuration with the heating blocks by adding tags?

like this:
```conf
heatingBlocks {
    "Block{minecraft:campfire[lit=true]}"=15
    "Block{minecraft:fire}"=3
    "Block{minecraft:lava}"=8
    "Block{minecraft:torch}"=3
    "Block{minecraft:wall_torch}"=3
}
```

love this mod, thanks :heart:

**Comment by Sparkierkan7** [comment]
I can prob fix this issue but no you can't add states to the blocks in the config yet. I'll look into adding block state configuration but CompleteConfig allows few different types so i don't know if its possible.
