### ISSUE TITLE
[suggestion]

### ISSUE THREAD

**Issue by benio1394** [Sparkierkan7/thermite_mod#14]
It would be a usefull feature to add option to add support/ config option to give some more armors heating or cooling tag. For example in immersive armors we have berserker armor crafted from leather and iron and looks like viking armor. It would have sence to give it heating attribute similar to armor armor. In the other hand we have a slime armor that could cool use in nether. Similar mechanic is pretty popular in temperature mods.

Maybe you could also add support for frostiful mod?

**Comment by Sparkierkan7** [comment]
This is already in the config. Leather armor is put in it already so just follow the same formatting when adding other armors and it and it should work.
