### ISSUE TITLE
Lava cauldrons should heat you like lava does (as default?)

### ISSUE THREAD

**Issue by LeyKlussyn** [Sparkierkan7/thermite_mod#15]
Hello,

I've loaded up the mod, and I was surprised when I wasn't heating near my lava cauldrons (cold biome). After digging a bit, I fixed it by simply adding it to the config myself.

```
heatingBlocks {
    ...
    "Block{minecraft:lava_cauldron}"=8
}
```

I'm not sure if it was left out by design. If it's intentional, feel free to close the issue. But I personally think it should be added to the default configuration of the mod. Thanks :)

**Comment by Sparkierkan7** [comment]
This is a bug. I guess I just forgot to add it to the default config.
