### ISSUE TITLE
Is this compatible with Autohud mod?

### ISSUE THREAD

**Issue by makumaku1974** [Sparkierkan7/thermite_mod#6]

**Comment by Sparkierkan7** [comment]
I don't think so, try it and find out.

**Comment by makumaku1974** [comment]
![2023-08-11_18 14 34](https://github.com/Sparkierkan7/thermite_mod/assets/129804277/916e9c6a-3cbe-4803-a42b-faa29bd5973e)
![2023-08-11_18 14 30](https://github.com/Sparkierkan7/thermite_mod/assets/129804277/6114808b-abdf-4aa1-a75a-f46bdef7e6bf)

I have 2 screenshots processed and the thermite temp is static as you can see. But it's just a suggestion for immersive purposes.

Accessibility -> Will it be configurable like able to change the percentage of when the Freezing or Heat effect damages?

Suggestion wise -> Freezing effect should start to appear as they go full bar and Heat effect is I guess primarily affecting critical damages such as burning.

Future plans -> Will you add more things to this amazing mod?

**Comment by Sparkierkan7** [comment]
Well ill look into adding compatibility but its not a guarantee that ill be able to do it. You could also ask the person who made autohud.

You can configure the mods damage range in version 3.2.0 and i do plan to add some sort of visual effect for when your too cold or hot.

**Comment by makumaku1974** [comment]
Thanks, I'll be looking forward to it.

**Comment by Sparkierkan7** [comment]
I couldn't figure out how to add compatibility directly but i have added a toggle keybind for the temperature display.
There is also a mod called [Amecs](https://modrinth.com/mod/amecs) that lets you bind multiple actions to the same key so you could set the dynamic hud toggle to the same key as the temperature display toggle with it.
