### ISSUE TITLE
crash with mod Concurrent Chunk Management Engine (Fabric)

### ISSUE THREAD

**Issue by Thebigboss537** [Sparkierkan7/thermite_mod#8]
when the Concurrent Chunk Management Engine (Fabric) mod is installed, after a few seconds in the game it disconnects from the world with the message "connection lost", the test is in singleplayer.

**Comment by Sparkierkan7** [comment]
Well i don't know how to fix this. I don't even know how Concurrent Chunk Management Engine works.
